name: cashhub
description: CashHub - ช้อปปิ้ง คืนเงิน แนะนำเพื่อนได้คอม
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  ios: '13.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  intl: ^0.20.2
  share_plus: ^10.1.1
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
